### ISSUE TITLE
dc_test

### ISSUE THREAD

**Issue by felixthoemmes** [felixthoemmes/rddapp#11]
- output from dc_test needs to be cleaned, formatted like summary function
- dc_test default should be verbose=TRUE
- plot from dc_test needs labels
- error message when bin is too large needs to be improved
- hangs when bin is too small - maybe potential fix for this

**Comment by zwenyu** [comment]
@felixthoemmes 
Just want to check with you if the following edits to the function will be fine:
- plot labels are 'Density Estimates' for y and runvar name for x
- added digits (decimal places to show) and level (for confidence interval) argument to dc_test
- when bin is too small, an "lm" function takes very long to run. I can set a fixed time limit for that function to run e.g. 1 min

**Comment by felixthoemmes** [comment]
All of these sound good.
Thanks!

**Comment by zwenyu** [comment]
Other instances (e.g. for loops) where program takes too long to run are found. Set timeout limit to 30s for each of these expressions.
