### ISSUE TITLE
mfrd_est

### ISSUE THREAD

**Issue by felixthoemmes** [felixthoemmes/rddapp#13]
When boot is larger than 10, we often get an error message about an extremely bad integrand and we need to investigate what is happening

**Comment by zwenyu** [comment]
Discussion about this issue:
https://stackoverflow.com/questions/40389482/numerical-integration-in-r-bad-integrand-behaviour-error
I tested that adding argument "stop.on.error = FALSE" solves the problem, although I'm not sure yet if this is the best solution

**Comment by felixthoemmes** [comment]
We should implement the following way: if a bad integrand happens, the function should not stop, but either (a) compute the bad integrand (user option for this "stop.on.error = FALSE"), or (b) discard this particular bootstrap sample, and continue the bootstrap. The user should be informed in the output how many (n out of total N bootstrap samples) and what percentage (n/N*100) of samples were bad.

**Comment by zwenyu** [comment]
Change in design choice: bootstrap till N successful bootstraps since user would probably want that number of samples, with printout stating number of discarded samples.
