### ISSUE TITLE
mfrd_est - ngrid default

### ISSUE THREAD

**Issue by felixthoemmes** [felixthoemmes/rddapp#19]
ngrid default seems kind of large (2500), maybe change default or check paper by Wong et al. why 2500 was chosen. 2500 makes this very slow, with less grid points, bootstrapping is actually pretty fast

**Comment by zwenyu** [comment]
@felixthoemmes Do you have the Stata MFRDD code that mfrd_est is modeled after?

**Comment by felixthoemmes** [comment]
Yes, let's ask Wang to send it to us, since he "translated" it.

**Comment by zwenyu** [comment]
@felixthoemmes Both the paper and the Stata code used the same default number, no explanation why they picked it. Running with smaller ngrid at say 250 changes the estimates slightly, <0.01 for the examples. Maybe we should add a note a line in the help file that ngrid can be lowered for faster computations?

**Comment by felixthoemmes** [comment]
Could you run a couple of other examples and confirm that using a smaller
grid also does not change much. If that is the case I'd suggest changing
the default to a smaller number

**Comment by zwenyu** [comment]
Changing default to 250. Checked effect on curtis_seed data, difference on estimates <0.01, difference on bounds of confidence interval can be larger but <0.1. Also adding note in help file that original parameter value used in reference paper is 2500.
