### ISSUE TITLE
mfrd_est  - arguments

### ISSUE THREAD

**Issue by felixthoemmes** [felixthoemmes/rddapp#20]
has a cluster option but by itself never computes clustered standard errors (it only does bootstraps), maybe remove this option? Does removing it break some other parts?

**Comment by zwenyu** [comment]
@felixthoemmes The standard errors are calculated from the bootstraps, according to clusters defined by the argument 'cluster'. So it does compute the correct standard errors?

**Comment by felixthoemmes** [comment]
Yes, in that case this appears to be correct. Thanks for checking.
