### ISSUE TITLE
download svg / jpeg

### ISSUE THREAD

**Issue by felixthoemmes** [felixthoemmes/rddapp#21]
Currently all plots can only be downloaded as PDFs. Users should be able to also download SVG or JPEGs - thoughts on which formats would be best?

**Comment by papsti** [comment]
Definitely SVG and PNG. SVG is scalable and I think many journals require it, while PNG is good for web (anything that involves text, features sharp lines, and has few colours--like plots). It's lossless, unlike JPEG, which can result in [ugly pixelation](https://user-images.githubusercontent.com/21325059/37728667-474b89b6-2d11-11e8-8111-45925fa85110.png). Also, there's this, which I fully agree with 🙃:

![file_extensions_2x](https://user-images.githubusercontent.com/21325059/37728805-952739aa-2d11-11e8-8d80-54bfff97d97b.png)

**Comment by papsti** [comment]
I've added buttons to download the power plot as either .png or .svg (see 9434374895b775b635ba99df62b14651de475f8b). Seems to work! Where else do we need these buttons?

**Comment by felixthoemmes** [comment]
Essentially, every time there is a button to download a graph as PDF. This
appears in Figure 2.1, Figure 3.1., Figure 4.1, Figure 4.2, and finally
Figure 5.1 (in the power section).

**Comment by papsti** [comment]
Done for figures:
* 2.1
* 3.1
