### ISSUE TITLE
demo using CARE data

### ISSUE THREAD

**Issue by papsti** [felixthoemmes/rddapp#22]
Should we create a demo of the software using the CARE data? I'm thinking the simplest would be a text demo (like a vignette in R, but just presented as a linked HTML document).  

If we did this, I would remove the material related to the CARE data from the help manual and instead just link to the demo from the help manual where relevant (e.g. in the Data section).

Thoughts?

**Comment by felixthoemmes** [comment]
The plan is to use the CARE dataset in the vignette. Once the vignette is
in place, this could be (easily?) transformed into an HTML. Or the two
could be done concurrently, and we could copy and paste among them as
needed.

**Comment by papsti** [comment]
This is now a duplicate thread (referenced in the main #26 now).
