### ISSUE TITLE
power function

### ISSUE THREAD

**Issue by felixthoemmes** [felixthoemmes/rddapp#25]
It seems that the power estimation relied on a default for t.design (or maybe even other defaults).
When this was changed in the rd_est or mfrd_est, the power function does not seem to work anymore. 
The assumption is that the power function relied on a default, but the power function should rely on the actual user input of the treatment assignment.

**Comment by felixthoemmes** [comment]
Also, once the function is fixed, it needs to properly interface with the shiny app. The user defines the design (larger, larger equal, smaller, smaller equal). If this proves difficult, Wang can probably help us easily.

**Comment by felixthoemmes** [comment]
@wliao229

**Comment by zwenyu** [comment]
@papsti I've fixed the rd_power function, and the power table/chart works now :) Played around with changing the parameters and the R code snippet changes accordingly. Just want to make sure it works for you too before I close this issue.
