### ISSUE TITLE
mfrd_est non-parametric

### ISSUE THREAD

**Issue by felixthoemmes** [felixthoemmes/rddapp#42]
mfrd_est frontier approach should have non-parametric version (see here: https://stats.stackexchange.com/questions/206476/how-to-choose-appropriate-bandwidth-for-kernel-regression/208071) 

This describes using cross-validation to choose bandwidth (which seems feasible). We could implement cross-validation, then estimate the model with chosen bandwidth h, and then use the exact same code (that forms all these predicted values along the grid of the frontier) to estimate effects. Inferential stats would come through bootstrapping again. I would suggest to choose the bandwidth once via CV, and then bootstrap with a fixed bw.

**Comment by zwenyu** [comment]
In fitting y (in mrd paper) by kernel regression, should we be using a bivariate kernel with the same bandwidth, or two kernels with possible different bandwidth?

**Comment by felixthoemmes** [comment]
That's the big question. If we want to estimate the frontier-specific
effect, of if we use the IV approach, or the centering approach, then we
are only looking at a single effect, and here we can use the same kernel
bandwidth of the single kernel density estimate (Imbens). For the weighted
frontier-effect (where you just get a single estimate for the whole
surface),  am thinking we should be using a bivariate kernel with a single
bandwidth. I don't think we can derive a plug-in bandwidth that balances
bias and variance, but if we were to attempt to estimate this at all, we
probably have to use cross-validation.

**Comment by zwenyu** [comment]
With reference to MRDS paper, for regions T1 and T3, distance measure will be the univariate distance from the relevant frontier. From region T2, use the Chebyshev distance from the intersections of the frontiers.

**Comment by felixthoemmes** [comment]
Or Euclidean distance for the region T2, if we prefer a smooth curve around
the intersection, and not a square box, like L_infinity (a.k.a.  Chebyshev)
.

**Comment by zwenyu** [comment]
A better implementation would be to use L1 to the frontier. Be careful to consider the treatment and nontreatment regions.
