### ISSUE TITLE
More example data in shiny app than described in help manual

### ISSUE THREAD

**Issue by papsti** [felixthoemmes/rddapp#44]
<img width="423" alt="screen shot 2018-06-19 at 1 13 36 pm" src="https://user-images.githubusercontent.com/21325059/41613113-af8254b8-73c2-11e8-8ee1-7c2d5866c599.png">
<img width="306" alt="screen shot 2018-06-19 at 1 13 53 pm" src="https://user-images.githubusercontent.com/21325059/41613114-af9167a0-73c2-11e8-84b2-ad356236bb41.png">

Are these real data that need to be discussed in the help manual/vignette or is it set to be removed? Is it a bug?

**Comment by felixthoemmes** [comment]
They are already gone in  shinyrddbeta.

We used them mostly for bugfixing and testing the app. 
f and s stands for fuzzy and sharp, 1 and 2 for the number of assignments, and cov and nocov whether a covariate is included or not.

**Comment by papsti** [comment]
Thanks for the clarification! I guess this leads to another question: which version of the `shiny` app are you looking at when you're writing the help manual? I want to make sure I'm looking at the same thing while editing.

**Comment by felixthoemmes** [comment]
Definitely the beta version.

**Comment by papsti** [comment]
@felixthoemmes maybe just double check that you're looking at the beta version when writing because I've found some clear references to the non-beta interface (e.g. "Upload Data" and "Model Specification" panels). Of course, this is early on in the help manual so may have been written a long time ago!

**Comment by felixthoemmes** [comment]
Ah yes, this was from a long time ago, and probably in reference to the
older version. I will go ahead and continue the draft version, then go back
to try to find those inconsistencies.

**Comment by papsti** [comment]
Don’t worry about going back — I’ve been correcting the inconsistencies as I edit because I have a window open with the beta version of the app open for reference while I edit 🙂

**Comment by felixthoemmes** [comment]
👍
