### ISSUE TITLE
Correct expression for the Gaussian kernel in the help manual?

### ISSUE THREAD

**Issue by papsti** [felixthoemmes/rddapp#45]
I don't think I understand the typesetting of the Gaussian kernel in `help_page.Rmd`, as written:

`Gaussian:     $K(u) = 1/\sqrt(2/\pi^-1/2u^2)$ `.

I'm specifically confused by what's supposed to be in the exponent on pi (`\pi^`)... If you reply with a quick snap of the handwritten equation (or a screenshot of it typeset somewhere), I can typeset it properly in `help_page.Rmd`. Thanks!

**Comment by felixthoemmes** [comment]
https://cran.r-project.org/web/packages/kedd/vignettes/kedd.pdf

page 2 - Table 1

**Comment by papsti** [comment]
Updated in b6c25d0defab09465540429db1f4b00afc201e76!
