### ISSUE TITLE
Covariate in model should not show Cohen's d

### ISSUE THREAD

**Issue by felixthoemmes** [felixthoemmes/rddapp#46]
If a covariate is added, the user can display the coefficient of that covariate. By default a Cohen's d is displayed. 
This should be suppressed. It is likely not meaningful for the researcher, and importantly, it is also wrong, because it is currently estimated based on the regression coefficient, and not a treatment effect estimate.

**Comment by zwenyu** [comment]
This should only be removed from the mrd_est and mfrd_est, and not from rd_est?

**Comment by zwenyu** [comment]
I see Cohen's d for rd_est is estimated from regression coefficient too, so should also be removed. It seems there is shiny function displaying Cohen's d, will this be affected?
