### ISSUE TITLE
include screenshots in help pages

### ISSUE THREAD

**Issue by papsti** [felixthoemmes/rddapp#5]

**Comment by papsti** [comment]
Screenshots are done for now--up to the Assumptions section. For some reason, when I try to get assumptions for the CARE data set (with the outcome variable set as `SBIQ48`, assignment rule set as IF `MOMWAIS0`>=85, and treatment receipt variable set as `DC_TRT`), nothing loads in the Assumptions tab...

**Comment by felixthoemmes** [comment]
Weird - this should work properly. Let's investigate tomorrow.

**Comment by felixthoemmes** [comment]
Actually, this one is easy. Assignment rule is < 85. Only kids whose mom's IQ was low, got the treatment.

**Comment by papsti** [comment]
Note to self: change height of screenshots to look good when window size is large.

**Comment by papsti** [comment]
Shelved for now -- help manual seems to read easily even without screenshots.
