### ISSUE TITLE
Errors when running an RDD with two assignment variables using CARE data

### ISSUE THREAD

**Issue by papsti** [felixthoemmes/rddapp#51]
I'm trying to run an RDD with two assignment variables in the `shiny` app with the CARE data, so that I can refer to the interface while editing that part of the help manual, but I'm getting errors trying to set everything up.

I used the "Sample data" section of [this doc](https://github.com/felixthoemmes/rddapp/blob/c56902b987ccf2db54361a773e37f539da7a7e80/inst/shinyrdd/help/help_page.Rmd) to set the RDD up.

I first set the outcome variable to `SBIQ48`, the treatment receipt variable to `DC_TRT`, and the treatment design to `MOMWAIS0` <= 85 and `APGAR5` <= 3, as specified in the above doc. However, it turns out that the sample of the CARE data currently included in the `shiny` beta app does not include any observations with `APGAR5` <= 3.

I increased the assignment threshold for `APGAR5` to 8 (so `APGAR5` <= 8 gets assigned to treatment), and while the tables in the Data tab all load properly, and I can check assumptions for the `MOMWAIS0` variable, I get an error for figure 2.1 saying "intitialization failed" when I try to perform McCrary's sorting test on the `APGAR5` variable. Moreover, all model estimation fails in the Estimates tab. I suspect there may be a problem using `DC_TRT` variable for treatment assignment in the case of this multiple assignment, and perhaps we'd need to dig up the old `RDD2_TR` column of data to get the RDD with two assignment variables to run.

I only bothered to write this up in detail since it also concerns the vignette/demo stuff, but for right now, I just need to be able to run an RDD with two assignment variables to edit the associated section in the help manual. Is there some quick fix you can think of?

**Comment by felixthoemmes** [comment]
Hi Irena,
Initially I was hoping to carve out an MRDD form the CARE data, but it proved to be too difficult. The sample size is simply way too small. Therefore I simulated some data.

**Comment by papsti** [comment]
Great, thanks for this!

Going forward, should we consider incorporating this simulated data as a demo data set for the multiple assignment RDD in the beta app? If so, I can create an issue and work on it first thing in the Fall term.

**Comment by felixthoemmes** [comment]
No bundled dataset that is simulated data. An unwritten rule of CRAN. If you can simulate with a couple lines of code, don’t add bulk to the program by including the simulated data. Our package help file should however include the sim code in an sample of the mrd_est function.

**Comment by felixthoemmes** [comment]
The simulated data works.
