### ISSUE TITLE
Add missing in-text citations to help_page.Rmd

### ISSUE THREAD

**Issue by papsti** [felixthoemmes/rddapp#55]
There are two instances in the doc where a citation year is given as (XXXX). Please add the years when you have a chance!

**Comment by papsti** [comment]
Added citations in 1e176aa6f8164c84a4f1e942f79fce80a98bca0e. For some reason, in the rendered html, BibLaTeX puts 3 em dashes as the authors of the second (2012) paper:

<img width="531" alt="screen shot 2018-09-10 at 7 53 30 pm" src="https://user-images.githubusercontent.com/21325059/45330421-65c26b80-b533-11e8-855c-83f3b8cc8331.png">

I'm sure that the author field of that BibTeX entry is properly defined, but I think the standard of this citation template is that identical authors don't get repeated in sequential entries. Is that standard practice in this field? @felixthoemmes, if you don't like it, I can try to get BibLaTeX to use a different citations template that doesn't do this.

**Comment by felixthoemmes** [comment]
It's not standard in psych, or ed (or primary targets). I am not sure about
econ, or soc.
If it is easy to change the biblatex template (as in changing a single
argument in some preamble), then yes, otherwise, we can stick with this.

**Comment by papsti** [comment]
Done in ba379d534ad942133b83c6f6f07cc12858aea4ba.
