### ISSUE TITLE
MRDDs non-param R output objects

### ISSUE THREAD

**Issue by felixthoemmes** [felixthoemmes/rddapp#57]
> Implement bandwidth choices closer to boundary - maybe 6-10 that are in the range of .5 sigma to 2 sigma - or implement randomly

> create output objects

**Comment by zwenyu** [comment]
Several downstream functions need to be updated due to the addition of arguments and change of outputs in mfrd_est and mrd_est e.g. mrd_impute, plot.mfrd. They currently only processes the parametric model.

**Comment by zwenyu** [comment]
Still need to update several downstream functions to incorporate results from nonparametric model e.g. plot.mfrd, mrd_impute. Currently these functions only runs on the parametric results.
