### ISSUE TITLE
Shiny Table 3.1 (summary of estimates) not displaying when using latest version of rddapp

### ISSUE THREAD

**Issue by papsti** [felixthoemmes/rddapp#60]
See screenshot:
<img width="1053" alt="screen shot 2018-10-24 at 1 23 38 pm" src="https://user-images.githubusercontent.com/21325059/47449159-f70e3a00-d78f-11e8-80ec-039e50aa35dc.png">

**Comment by papsti** [comment]
Still get this error with our dummy data (which has many more pts so avoiding any other numerical errors). Troubleshooting this first before trying to add new estimates for nonparametric frontier.

**Comment by papsti** [comment]
The issue is in how `tab_front` is created in `model_estimate.R`. 

It needs to be compatible to `rbind` with `tab_center`, `tab_univ1`, and `tab_univ2`, all of which have 11 "variables" (columns for display) with the headers: `"label" "bw"    "n"     "est"   "se"    "z"     "df"    "p"     "l95"   "es"    "type"`. They also get created with 8 "variables", which correspond to the labels `"Parametric"       "- Linear"         "- Quadratic"      "- Cubic"          "Nonparametric"    "- Optimal"       "- Half-Optimal"   "- Double-Optimal"`

In initializing `tab_front` with the call to `data.frame()`, something gets corrupted and we create 43 variables, a lot of which are `NA`. 

What we actually want is to create `tab_front` with 11 variables and 26 "observations", where the observations are taken from three levels:
1. `"Parametric"` or `"Nonparametric"`
2. `"- Average"` or `"- Frontier 1"` or `"- Frontier 2"`
3. `"-- Unconstrained"` or `"-- Heterogeneous Effect"` or `"-- Constant Effect"`
All combos of the above lead to 26 "observations".

That's what needs to be done next!

**Comment by papsti** [comment]
Following discussions with Wenyu, I better understand the structure of the model output for the frontier design. For example, in any given row of `result$model()$front$tau_MRD$est`, we have the estimates for all nine cases (last two levels of organization from last comment in this thread, e.g. average + unconstrained). The rows are parametric, nonparametric (optimal), nonparametric (half-bandwidth), nonparametric (double-bandwidth).

**Comment by papsti** [comment]
@zwenyu, I see that you added the observation number as output of `mfrd_est()` in commit 62cb66140da71fec61ffc8554781aa033c0ffe03, but when I try to access this output in shiny by printing the object `result$model()$front$tau_MRD$obs`, I get `NULL`... any idea why this might be happening? We can look at this together in the meeting tomorrow.

**Comment by zwenyu** [comment]
You'll need to re-install the package from github by devtools::install_github("felixthoemmes/rddapp")

**Comment by papsti** [comment]
Ah! Why do I always forget this?? Thanks!

**Comment by papsti** [comment]
Added observation numbers and confidence intervals in Table 3.1 with daac723a6040d5a5b780a5416b2e6144564bc14a, but have to double check tomorrow in meeting if everything is correctly labeled based on `mrd_est()` output.

**Comment by papsti** [comment]
Fixed with c918164eb881c2fd5d36f5eceb6786fd92fe99e0 (except for Cohen's d)

**Comment by papsti** [comment]
Added Cohen's d with a606745c79863ee62a08e7a3c32a9d7d6c616280. Done!
