### ISSUE TITLE
Plotting covariates that are factors is not possible

### ISSUE THREAD

**Issue by timcashion** [felixthoemmes/rddapp#71]
First, thanks for this great package. 

I may be missing something here (I'm not a statistician), but the plot.rd function does not work if the covariate you have specified is a factor. I traced the error to the predict.rd function within plot.rd at this point (Lines 95-101 of predict.rd.R)

```
# ADD COVS AT GRAND MEAN 
  if (!is.null(object$cov)) {
    covs_gm <- paste0(object$cov, "_gm")
    df_p <- cbind(df_p, 
                  setNames(lapply(subset(object$frame, select = object$cov), mean, na.rm = TRUE), nm = covs_gm))
  } else {
    covs_gm <- c()
  }
```
Unsurprisingly, calling `mean` on a factor yields NAs. Then when the code tries to use this later in the code it leads to the following error:
"Error in `contrasts<-`(`*tmp*`, value = contrasts.arg[[nn]]) : contrasts apply only to factors"

Now, thinking about this I don't know what I would expect to see. I would like the model I am making to be able to include these covariates that are factors, but what would the plot look like? Would it choose the reference level factor (i.e., base case) and form the prediction based on that? 

I've included a reproducible example below:
```
df <- tibble(x = rep(seq(-5, 5, 1), 3),
       y = rnorm(33, mean=1, sd=0.1),
       f = factor(c(rep("A", 11), rep("B", 11), rep("C", 11))))
df$z <- 0
df$z[df$x >=0 ] <- 1

rd <- rd_est(y ~ x + z|f, 
       t.design = 'geq',
       data=df)
plot(rd)
```

**Comment by felixthoemmes** [comment]
Hi Tim,
Thanks for opening our first issue (by somebody who has not on the dev team)!
The pandemic is slowing us all down a bit, but I am hoping that I will be able to look into this within the next coming week. Unfortunately this won't be a quick fix, but we appreciate the feedback!

**Comment by felixthoemmes** [comment]
Error catching for this has been added, no plot being produced.
