### ISSUE TITLE
rddapp for R4?

### ISSUE THREAD

**Issue by axlehner** [felixthoemmes/rddapp#72]
Hi,
I was just wondering whether you plan to fix the check problem to get the package on CRAN again for R4? (A package of mine partly depends on it. It is not urgent, but if I knew that you are not going to maintain it, then i could remove it already now)
Would be a pitty if not, it is a cool package!

Cheers

**Comment by felixthoemmes** [comment]
Hi,
I am sort of in the same boat. I have a smallish dependency on rddtools,
that also got delisted from CRAN. A couple of weeks ago the rddtools
maintainers told me they would be back on CRAN soon. So I held off until
they were back on CRAN. Eventually I have to make a decision to either wait
longer, or incorporate some of their functions in rddtools.
The ultimate goal is to get back on CRAN. I would love to say that it's
going to be soon, but I can't promise it.
Hope this helps,
Felix

**Comment by axlehner** [comment]
Thanks a lot! I did not even realise the thing with rddtools yet. I poked them as well again. Probably that helps.

**Comment by felixthoemmes** [comment]
Hoping to resubmit to CRAN next week.
