### ISSUE TITLE
clean up repo from help page TOC fiddling and create script to neatly knit help manual html into www folder

### ISSUE THREAD

**Issue by papsti** [felixthoemmes/rddapp#9]

**Comment by papsti** [comment]
@felixthoemmes, do you work in the command line as well as R studio when you're coding, or do you just stick within RStudio? I'm just trying to figure out what would be easier for you to compile the help manual document after edits into html that gets read by shiny:
* typing `make help` (or something similar) into the command line, whose present working directory is the `shinyrdd` folder,
* an R script that you can source in the R console.

Let me know which you find more convenient and I'll code it up that way.

**Comment by felixthoemmes** [comment]
I am mostly an Rstudio guy, so probably sourcing it.

**Comment by papsti** [comment]
Done! See instructions for how to compile the help doc for shiny after working on it in #3.
